"use client";
import Link from"next/link";
import{BookOpen,Heart,Plus,Sparkles,Users}from"lucide-react";
import{useEffect,useState}from"react";
import{CharacterPoster,StoryPoster}from"@/components/content-card";
import{HttpApiClient,type ApiBot}from"@/lib/api";
import type{StorySummary}from"@/lib/types";
const api=new HttpApiClient();
export default function CollectionPage(){const[section,setSection]=useState<"created"|"favorites">("created"),[kind,setKind]=useState<"characters"|"stories">("characters"),[bots,setBots]=useState<ApiBot[]>([]),[stories,setStories]=useState<StorySummary[]>([]);useEffect(()=>{Promise.allSettled([api.getMyBots(),api.getMyStories()]).then(([a,b])=>{if(a.status==="fulfilled")setBots(a.value);if(b.status==="fulfilled")setStories(b.value)})},[]);const empty=section==="favorites"||(kind==="characters"?!bots.length:!stories.length);return <main className="page-wrap"><header className="collection-head"><div><div className="title-tabs"><button onClick={()=>setSection("created")} className={section==="created"?"active":""}>Созданное</button><span>|</span><button onClick={()=>setSection("favorites")} className={section==="favorites"?"active":""}>Избранное</button></div><p>Ваша творческая коллекция</p></div><div className="create-menu"><Link href="/create"><Plus size={16}/>Персонаж</Link><Link href="/stories/new"><BookOpen size={16}/>История <small>бета</small></Link></div></header><div className="segmented"><button onClick={()=>setKind("characters")} className={kind==="characters"?"active":""}><Users size={17}/>Персонажи <small>{section==="created"?bots.length:0}</small></button><button onClick={()=>setKind("stories")} className={kind==="stories"?"active":""}><BookOpen size={17}/>Истории <small>{section==="created"?stories.length:0}</small></button></div>{empty?<div className="empty-panel large"><span>{section==="favorites"?<Heart/>:kind==="characters"?<Users/>:<Sparkles/>}</span><h2>{section==="favorites"?"В избранном пока пусто":kind==="characters"?"Пока нет своих персонажей":"Пока нет своих историй"}</h2><p>{section==="favorites"?"Сохраняйте понравившийся контент в каталоге":"Создайте первый проект — он появится здесь"}</p>{section==="created"&&<Link href={kind==="characters"?"/create":"/stories/new"} className="soft-primary">Создать {kind==="characters"?"персонажа":"историю"}{kind==="stories"&&<small>бета</small>}</Link>}</div>:<div className="collection-grid">{kind==="characters"?bots.map((item,index)=><CharacterPoster key={item.id} item={item} index={index}/>):stories.map((item,index)=><StoryPoster key={item.id} item={item} index={index}/>)}</div>}</main>}
