"use client";import{useCallback,useEffect,useRef,useState,type ChangeEvent,type ClipboardEvent,type FormEvent,type KeyboardEvent}from"react";import Link from"next/link";import{useRouter}from"next/navigation";import{Turnstile,type TurnstileHandle}from"@/components/turnstile";import{BrandMark}from"@/components/brand-mark";import{Field,inputClass}from"@/components/ui";import{HttpApiClient,ApiError,getApiUrl}from"@/lib/api";import{storeSession}from"@/lib/session";
const api=new HttpApiClient(),siteKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY??"",captchaEnabled=process.env.NEXT_PUBLIC_CAPTCHA_ENABLED==="true";
let warmDone=false,warmP:Promise<void>|null=null;
function startWarm(){if(!warmP)warmP=(async()=>{try{await fetch(getApiUrl("/api/capabilities"),{cache:"no-store",signal:AbortSignal.timeout(55_000)});warmDone=true}catch{}})();return warmP}
async function withRetry<T>(fn:()=>Promise<T>,retries=2):Promise<T>{if(!warmDone&&warmP)try{await warmP}catch{};for(let i=0;i<=retries;i++){try{return await fn()}catch(e){if(i===retries||e instanceof ApiError)throw e;await new Promise(r=>setTimeout(r,3000))}}throw new Error("Ошибка")}
type Mode="register"|"login";type AuthSession={user:{id:string;email:string};session:{accessToken:string;refreshToken:string}};
const EMPTY=["","","","","",""];
export default function AuthPage(){const router=useRouter(),ref=useRef<TurnstileHandle>(null);useEffect(()=>{startWarm()},[]);
const[mode,setMode]=useState<Mode>("register"),[animKey,setAnimKey]=useState(0),[slide,setSlide]=useState<"none"|"left"|"right">("none"),[step,setStep]=useState<"email"|"code">("email"),[email,setEmail]=useState(""),[name,setName]=useState(""),[password,setPassword]=useState(""),[terms,setTerms]=useState(false),[news,setNews]=useState(false),[captcha,setCaptcha]=useState<string|null>(captchaEnabled?null:"captcha-disabled"),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
const[digits,setDigits]=useState<string[]>(EMPTY),[activeBox,setActiveBox]=useState(0);const boxRefs=useRef<Array<HTMLInputElement|null>>([]);const code=digits.join("");const token=useCallback((x:string|null)=>setCaptcha(x),[]);
function writeDigit(i:number,value:string){const clean=value.replace(/\D/g,"");if(clean.length>1){const next=EMPTY.map((_,k)=>clean[k]??"");setDigits(next);const focus=Math.min(clean.length,5);boxRefs.current[focus]?.focus();setActiveBox(focus);return}setDigits(prev=>{const next=[...prev];next[i]=clean;if(clean&&i<5){boxRefs.current[i+1]?.focus();setActiveBox(i+1)}return next})}
function boxKeyDown(i:number,e:KeyboardEvent<HTMLInputElement>){if(e.key==="Backspace"&&!digits[i]&&i>0){setDigits(prev=>{const next=[...prev];next[i-1]="";return next});boxRefs.current[i-1]?.focus();setActiveBox(i-1)}}
function boxPaste(e:ClipboardEvent<HTMLInputElement>){e.preventDefault();const clean=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(!clean)return;const next=EMPTY.map((_,k)=>clean[k]??"");setDigits(next);const focus=Math.min(clean.length,5);boxRefs.current[focus]?.focus();setActiveBox(focus)}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{if(step==="email"){if(captchaEnabled&&!captcha)throw new Error("Подтвердите, что вы не робот");if(mode==="register"){if(!terms)throw new Error("Подтвердите согласие с условиями использования");await withRetry(()=>api.requestOtp({email,purpose:"register",captchaToken:captcha??"captcha-disabled",displayName:name,password,isAdultConfirmed:true,termsAccepted:true,newsletterOptIn:news}));setStep("code");setDigits(EMPTY);setActiveBox(0)}else finish(await withRetry(()=>api.login({email,password})))}else finish(await withRetry(()=>api.verifyOtp({email,purpose:"register",code})))}catch(x){const isNetErr=x instanceof Error&&(x.message==="Load failed"||x.message.includes("NetworkError")||x.message.includes("fetch"));const msg=x instanceof ApiError?x.message:isNetErr?"Сервер просыпается. Попробуйте ещё раз через пару секунд.":x instanceof Error?x.message:"Ошибка";setError(msg);ref.current?.reset()}finally{setBusy(false)}}
function finish(r:AuthSession){storeSession({...r.session,userId:r.user.id,email:r.user.email});router.replace((()=>{const next=new URLSearchParams(window.location.search).get("next");return next?.startsWith("/")?next:"/"})())}
function switchMode(x:Mode){setSlide(x==="login"?"right":"left");setMode(x);setStep("email");setError(null);setAnimKey(k=>k+1);ref.current?.reset()}
const formClass=`mt-6 grid gap-4 ${slide==="left"?"auth-form-from-left":slide==="right"?"auth-form-from-right":"auth-form-animated"}`;
return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><BrandMark className="h-16 w-16"/><span>IskraAi</span></div>
{step==="code"?<><h1 className="display text-center text-3xl font-semibold text-white">Код из письма</h1><p className="mt-3 text-center text-sm text-stone-400">Отправили 6 цифр на {email}. Код действует 10 минут.</p><div className="otp-boxes">{EMPTY.map((_,i)=>(<input key={i} ref={el=>{boxRefs.current[i]=el}}className={"otp-box"+(i===activeBox?" is-active":"")}inputMode="numeric"autoComplete="one-time-code"maxLength={6}value={digits[i]}onFocus={()=>setActiveBox(i)}onChange={(e:ChangeEvent<HTMLInputElement>)=>writeDigit(i,e.target.value)}onKeyDown={(e:KeyboardEvent<HTMLInputElement>)=>boxKeyDown(i,e)}onPaste={boxPaste}disabled={busy}aria-label={`Цифра ${i+1}`}/>))}</div></>:<><h1 className="display text-center text-3xl font-semibold text-white">{mode==="register"?"Создай аккаунт":"С возвращением"}</h1><p className="mt-3 text-center text-sm text-stone-400">{mode==="register"?"Персонажи, диалоги и истории ждут":"Войди, чтобы продолжить общение"}</p><div className="auth-tabs"><span aria-hidden="true" className={"auth-tabs-pill"+(mode==="login"?" is-login":"")}></span><button type="button" onClick={()=>switchMode("register")} aria-selected={mode==="register"}>Регистрация</button><button type="button" onClick={()=>switchMode("login")} aria-selected={mode==="login"}>Вход</button></div></>}
<form key={animKey} className={formClass} onSubmit={submit}>{step==="email"?<>{mode==="register"&&<Field label="Имя или псевдоним"><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} className={`${inputClass} auth-input`} autoComplete="nickname"/></Field>}<Field label="Электронная почта"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className={`${inputClass} auth-input`} autoComplete="email"/></Field><Field label="Пароль"><input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} className={`${inputClass} auth-input`} autoComplete={mode==="register"?"new-password":"current-password"}/></Field>
{mode==="register"&&<><label className="auth-check"><input required type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Я прочитал(а) и принимаю <Link href="/privacy/" target="_blank" className="font-semibold text-white underline underline-offset-4">политику конфиденциальности</Link> и <Link href="/legal/" target="_blank" className="font-semibold text-white underline underline-offset-4">условия использования</Link>.</span></label><label className="auth-check"><input type="checkbox" checked={news} onChange={e=>setNews(e.target.checked)}/><span>Получать новости</span></label></>}
{captchaEnabled&&<div className="turnstile-wrap">{siteKey?<Turnstile ref={ref} siteKey={siteKey} onTokenChange={token}/>:<p className="auth-error">Проверка безопасности не настроена</p>}</div>}</>:null}{error&&<p className="auth-error">{error}</p>}<button className="auth-submit" disabled={busy||(step==="email"&&((captchaEnabled&&!captcha)||password.length<8||mode==="register"&&(!terms||!name)))}>{busy?"Подождите…":step==="email"?(mode==="register"?"Создать аккаунт":"Войти"):"Подтвердить"}</button>{step==="code"&&<button type="button" className="text-sm text-stone-400" onClick={()=>{setStep("email");setDigits(EMPTY);setError(null);ref.current?.reset()}}>Изменить почту</button>}</form></section></main>}
