"use client";
import Link from"next/link";
import{ArrowRight,BookOpen,Plus,Sparkles}from"lucide-react";
import{useEffect,useState}from"react";
import{CharacterPoster,StoryPoster}from"@/components/content-card";
import{HttpApiClient,type ApiBot}from"@/lib/api";
import type{StorySummary}from"@/lib/types";
const api=new HttpApiClient();
export default function Home(){const[bots,setBots]=useState<ApiBot[]>([]),[stories,setStories]=useState<StorySummary[]>([]),[error,setError]=useState<string|null>(null);useEffect(()=>{let active=true;Promise.allSettled([api.getBots(),api.getStories()]).then(([botResult,storyResult])=>{if(!active)return;if(botResult.status==="fulfilled")setBots(botResult.value);else setError("Не удалось загрузить персонажей");if(storyResult.status==="fulfilled")setStories(storyResult.value)});return()=>{active=false}},[]);return <main className="page-wrap"><section className="home-hero"><div><span className="eyebrow"><Sparkles size={14}/>IskraAi</span><h1>Начните новую историю</h1><p>Выберите героя или авторский сюжет. Ваши решения меняют происходящее.</p><div className="hero-actions"><Link href="/catalog" className="soft-primary"><BookOpen size={18}/>Каталог</Link><Link href="/create" className="soft-secondary"><Plus size={18}/>Создать</Link></div></div><div className="hero-orbit" aria-hidden="true"><span>✦</span><i/><b>Истории<br/>отвечают</b></div></section>{error&&<p className="notice-error">{error}</p>}<Rail title="Популярные персонажи" href="/catalog">{bots.slice(0,8).map((item,index)=><CharacterPoster key={item.id} item={item} index={index}/>)}</Rail><Rail title="Истории" href="/catalog?type=stories">{stories.length?stories.slice(0,6).map((item,index)=><StoryPoster key={item.id} item={item} index={index}/>):<Link className="empty-rail" href="/stories/new"><BookOpen/>Создать первую историю <small>бета</small></Link>}</Rail></main>}
function Rail({title,href,children}:{title:string;href:string;children:React.ReactNode}){return <section className="content-rail"><header><h2>{title}</h2><Link href={href}>Все <ArrowRight size={16}/></Link></header><div className="rail-scroll">{children}</div></section>}
