"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BookOpen,Compass,Home,Library,Menu,Plus,UserRound,X } from "lucide-react";
import { useEffect,useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { cn } from "@/lib/utils";
import { hasCachedSession } from "@/lib/session";
const links=[{href:"/",label:"Главная",icon:Home},{href:"/catalog",label:"Каталог",icon:Compass},{href:"/creator",label:"Коллекция",icon:Library},{href:"/profile",label:"Профиль",icon:UserRound}];
export function Header(){const path=usePathname();const[open,setOpen]=useState(false);const[loggedIn,setLoggedIn]=useState(false);useEffect(()=>setOpen(false),[path]);useEffect(()=>setLoggedIn(hasCachedSession()),[path]);if(path.startsWith("/auth")||path.startsWith("/register"))return null;return <><aside className={cn("side-nav",open&&"is-open")}><div className="side-brand"><Link href="/" className="flex items-center gap-3"><BrandMark className="size-10"/><b>IskraAi</b></Link><button className="side-close" onClick={()=>setOpen(false)} aria-label="Закрыть меню"><X/></button></div><nav className="side-links" aria-label="Основная навигация">{links.map(item=>{const Icon=item.icon;const active=item.href==="/"?path===item.href:path.startsWith(item.href);return <Link key={item.href} href={item.href} className={cn("side-link",active&&"is-active")}><Icon size={19}/><span>{item.label}</span></Link>})}</nav><div className="side-create"><Link href="/create" className="side-create-link"><Plus size={18}/>Создать персонажа</Link><Link href="/stories/new" className="side-create-link"><BookOpen size={18}/><span>Создать историю <small>бета</small></span></Link></div><div className="side-account">{loggedIn?<Link href="/profile" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[var(--accent)] text-sm font-black text-[var(--accent-ink)]">Я</span><span><b className="block text-sm">Мой профиль</b><small className="text-[var(--muted)]">Настройки</small></span></Link>:<Link href="/auth" className="side-create-link">Войти</Link>}</div></aside><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Открыть меню"><Menu/></button>{open&&<button className="nav-scrim" onClick={()=>setOpen(false)} aria-label="Закрыть меню"/>}</>}
