"use client";
import Link from"next/link";
import{usePathname}from"next/navigation";
import{BookOpen,Compass,Headphones,Home,Library,Menu,Moon,Plus,Sun,UserRound,X}from"lucide-react";
import{useEffect,useMemo,useState}from"react";
import{BrandMark}from"@/components/brand-mark";
import{cn}from"@/lib/utils";
import{hasCachedSession}from"@/lib/session";
import{HttpApiClient}from"@/lib/api";
import type{UserProfile}from"@/lib/types";
const api=new HttpApiClient();
const links=[{href:"/",label:"Главная",icon:Home},{href:"/catalog",label:"Каталог",icon:Compass},{href:"/creator",label:"Коллекция",icon:Library},{href:"/profile",label:"Профиль",icon:UserRound}];
function initials(name:string){return name.trim().split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join("").toUpperCase()||"Я"}
export function Header(){const path=usePathname();const[open,setOpen]=useState(false),[loggedIn,setLoggedIn]=useState(false),[profile,setProfile]=useState<UserProfile|null>(null),[theme,setTheme]=useState<"dark"|"light">("dark");useEffect(()=>setOpen(false),[path]);useEffect(()=>{const authenticated=hasCachedSession();setLoggedIn(authenticated);if(authenticated)api.getProfile().then(setProfile).catch(()=>setProfile(null))},[path]);useEffect(()=>{const saved=window.localStorage.getItem("iskra-theme-v2")==="light"?"light":"dark";setTheme(saved);document.documentElement.dataset.theme=saved},[]);function toggleTheme(){const next=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;window.localStorage.setItem("iskra-theme-v2",next)}const accountInitials=useMemo(()=>initials(profile?.displayName??""),[profile]);if(path.startsWith("/auth")||path.startsWith("/register"))return null;return <><aside className={cn("side-nav",open&&"is-open")}><div className="side-brand"><Link href="/" className="flex items-center gap-3"><BrandMark className="size-10"/><b>IskraAi</b></Link><button className="side-close" onClick={()=>setOpen(false)} aria-label="Закрыть меню"><X/></button></div><nav className="side-links" aria-label="Основная навигация">{links.map(item=>{const Icon=item.icon;const active=item.href==="/"?path===item.href:path.startsWith(item.href);return <Link key={item.href} href={item.href} className={cn("side-link",active&&"is-active")}><Icon size={19}/><span>{item.label}</span></Link>})}</nav><div className="side-create"><Link href="/create" className="side-create-link"><Plus size={18}/>Создать персонажа</Link><Link href="/stories/new" className="side-create-link"><BookOpen size={18}/><span>Создать историю <small>бета</small></span></Link></div><div className="side-account"><a className="theme-toggle" href="mailto:support@kiripilot.ru?subject=Поддержка%20IskraAi"><Headphones size={18}/><span>Поддержка</span></a><button className="theme-toggle" onClick={toggleTheme}>{theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}<span>{theme==="dark"?"Светлая тема":"Тёмная тема"}</span></button>{loggedIn?<Link href="/profile" className="account-link"><span className="grid size-10 place-items-center rounded-full bg-[var(--accent)] text-sm font-black text-[var(--accent-ink)]">{accountInitials}</span><span className="min-w-0"><b className="truncate">{profile?.displayName||"Загружаем профиль…"}</b><small className="truncate">{profile?.email||"Настройки"}</small></span></Link>:<Link href="/auth" className="side-create-link">Войти</Link>}</div></aside><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Открыть меню"><Menu/></button>{open&&<button className="nav-scrim" onClick={()=>setOpen(false)} aria-label="Закрыть меню"/>}</>}
